image: node:8
stages:
    - production

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    # The provider option specifies the provider that we want to deploy
    # The app option sets the Heroku app name
    # api-key option sets the Heroku API key
    - dpl --provider=heroku --app=node-talal --api-key=$HEROKU_API_KEY
  only:
    - master
